[package]
name = "kujira-ghost"
version = "1.1.0"
edition = "2021"
authors = ["Kujira Labs"]
description = "Interfaces for Kujira GHOST"
license = "Apache-2.0"
repository = "https://github.com/Team-Kujira/kujira-rs/tree/master/packages/kujira-ghost"

[dependencies]
cosmwasm-std = { workspace = true }
cw-utils = { workspace = true }
cosmwasm-schema = { workspace = true }
kujira-fin = { path = "../kujira-fin", version = "1.1.0" }
kujira-std = { path = "../kujira-std", version = "1.1.0" }
