[package]
name = "kujira-ghost"
version = "0.8.3"
edition = "2021"

[dependencies]
cosmwasm-std = { workspace = true, version = "1.2" }
cw-utils = { workspace = true, version = "1.0" }
cosmwasm-schema = { workspace = true, version = "1.2" }
kujira-std = { path = "../kujira-std", version = "0.8" }
