[package]
name = "kujira-rs-testing"
version = "1.6.0"
authors = ["Kujira Labs"]
edition = "2018"
description = "Interfaces and utilities for Kujira cosmwasm contracts"
license = "Apache-2.0"
homepage = "https://kujira.app"
repository = "https://github.com/Team-Kujira/kujira-rs"

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true, features = ["cosmwasm_1_2"] }
cosmwasm-schema = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, default-features = false, features = ["derive"] }
cw-multi-test = { version = "0.18", features = ["cosmwasm_1_2"] }
cw-storage-plus = "1.1"
anyhow = { workspace = true }
kujira = "0.10.0"
serde_json = { workspace = true }
base64 = "0.20.0"
hex = { workspace = true }
cw20 = { workspace = true }
sha2 = "0.10.8"
bech32 = "0.9.1"
