[package]
name = "kujira-pilot"
version = "1.0.1"
edition = "2021"
authors = ["Kujira Labs"]
description = "Interfaces for Kujira PILOT"
license = "Apache-2.0"
repository = "https://github.com/Team-Kujira/kujira-rs/tree/master/packages/kujira-pilot"

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw20 = { workspace = true }
kujira-std = { path = "../kujira-std", version = "1.0.0" }
kujira-orca = { path = "../kujira-orca", version = "1.0.0" }
